fix: Correctly resolve macOS SDK paths
bazel-contrib/rules_python pull request #2478
Opened 2024-12-06 16:26 UTC by shs96c

XCode has facilities for accurately telling us where SDKs are installed. This is important to use, particularly when there may be multiple SDKs or versions of XCode installed.

2024-12-07 02:39 UTC, aignas reviewed
LGTM, but please include a CHANGELOG note about the changed behaviour on the MacOS platforms.

2024-12-07 02:39 UTC, aignas commented on python/private/pypi/whl_library.bzl
> +        xcode_sdk_path = "{}/SDKs/MacOSX.sdk".format(xcode_root)
Thinking out loud, is this path absolute? I am wondering if we should have the path in the `rules_python_internal` where we then can include the path by importing it as a constant.

2024-12-07 02:39 UTC, aignas commented on python/private/pypi/whl_library.bzl
> +    if not rctx.attr.download_only:
Let's also exclude when the `filename` is specified and it is a `whl`.

2024-12-07 22:53 UTC, rickeylev requested changes

2024-12-07 22:53 UTC, rickeylev commented on python/private/pypi/whl_library.bzl
> +        xcode_sdks_json = rctx.execute([
Please use `repo_utils.execute_checked` from `//python/private:repo_utils.bzl. We have wrappers that do some book keeping to aid debugging etc. (See a few lines above for example)

2024-12-07 22:53 UTC, rickeylev commented on python/private/pypi/whl_library.bzl
> +    # In those cases, we're limited to --donwload-only, but we should respect that here.
```suggestion
    # In those cases, we're limited to --download-only, but we should respect that here.
```

2025-03-07 05:45 UTC, aignas approved these changes
LGTM

2025-03-25 02:30 UTC, rickeylev approved these changes

2025-03-25 02:46 UTC, merged